### ISSUE TITLE
[BUG] evaluation fails everytime ( it works in console) and some bugs mentioned

### ISSUE THREAD

**Issue by nandish486** [kaliiiiiiiiii/undetected-playwright-python#12]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from undetected_playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
     page.wait_for_load_state('DOMContentLoaded')
     page.evaluate('document.querySelector("#recaptcha-anchor > div.recaptcha-checkbox-border").click()')

    #...

    browser.close()
```

**Steps**
  navigate to recapthca site and try to click by playwright
**Expected**

click on recaptcha box, 

**Actual**

it shows nonetype has no method click(), u verified with sleep(100) and executing script, it works if i inspect element

Also undetected playwight after loading scripts fails to execute page.evaluate('grecaptcha.execute();') although it is loaded and works nice on console.

there are many more errors regarding page.evaluate which is not working with undetected playwright, i tried same for  normal playwright and it works,

i hope issues regarding js and execution solve soon.

Ignore typos here, i maked sure everything is correct at my end

**Comment by kaliiiiiiiiii** [comment]
> **Test file (self-contained)**
> 
> ```python
> from undetected_playwright.sync_api import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch()
>     page = browser.new_page()
>     # ...
>      page.wait_for_load_state('DOMContentLoaded')
>      page.evaluate('document.querySelector("#recaptcha-anchor > div.recaptcha-checkbox-border").click()')
> 
>     #...
> 
>     browser.close()
> ```

`.click()` with JS is detectable 
> Also undetected playwight after loading scripts fails to execute page.evaluate('grecaptcha.execute();') although it is loaded and works nice on console.

All js is evaluated inside an `isolatedWorld` to avoid detection. https://github.com/kaliiiiiiiiii/undetected-playwright-python/issues/5#issue-2034334367

> there are many more errors regarding page.evaluate which is not working with undetected playwright, i tried same for normal playwright and it works,

likely, all of them are gonna be fixed when https://github.com/kaliiiiiiiiii/undetected-playwright-python/issues/5#issue-2034334367 is resolved, therefore closing for now
