### ISSUE TITLE
[BUG] Leaking CDP Runtime Domain on Persistent Context

### ISSUE THREAD

**Issue by Vinyzu** [kaliiiiiiiiii/undetected-playwright-python#3]
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from tempfile import TemporaryDirectory

from playwright.sync_api import sync_playwright

temp_dir = TemporaryDirectory()
temp_dir_path = temp_dir.name

with sync_playwright() as p:
    args = ["--disable-blink-features=AutomationControlled"]
    browser = p.chromium.launch_persistent_context(user_data_dir=temp_dir_path, args=args, headless=False, channel="chrome")
    page = browser.new_page()
    page.goto("https://hmaker.github.io/selenium-detector/")
    input("Press ENTER to exit:")
    browser.close()

temp_dir.cleanup()
```

**Steps**
- [Run the test]
- [...]

**Expected**

Should not have any Detection, as its the case without a Persistent Context.

**Actual**

The CDP Runtime Domain leaks and gets detected,

**Comment by kaliiiiiiiiii** [comment]
Can't really reproduce that - at least not with the runtime domain.
![image](https://github.com/kaliiiiiiiiii/undetected-playwright-python/assets/89038706/02d3bbfd-f558-491b-a993-929fb3d24630)

what I did forget indeed is `ignoreDefaultArgs=['--enable-automation']` for it, but added it now (=> next release)

soo with that fixed, the following script works just fine for me:
```python
import time
from tempfile import TemporaryDirectory

from undetected_playwright.sync_api import sync_playwright

temp_dir = TemporaryDirectory()
temp_dir_path = temp_dir.name

with sync_playwright() as p:
    args = ["--disable-blink-features=AutomationControlled"]
    browser = p.chromium.launch_persistent_context(user_data_dir=temp_dir_path, args=args, headless=False, channel="chrome")
    page = browser.new_page()
    page.goto("https://nowsecure.nl/#relax")
    input()
    browser.close()

temp_dir.cleanup()
```

**Comment by kaliiiiiiiiii** [comment]
@Vinyzu Please test this again with https://pypi.org/project/undetected-playwright-patch/1.40.0.post1700587210000/ and close this issue if it's resolved now:)
